/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ikinci.deneme;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.Soundbank;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author HP
 */
public class AYARLAREKANÝ extends javax.swing.JFrame {

    /**
     * Creates new form AYARLAREKANÝ
     */
    public AYARLAREKANÝ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        deðiþtirici = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\PROJE DOSYALARI\\giphy (1).gif")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\PROJE DOSYALARI\\giphy (1).gif")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Müzik Düzeyi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 90));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Diger Sarkilar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 60));

        ComboBox.setBackground(new java.awt.Color(51, 51, 51));
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SideWalks And Skeletons", "SleepWalker", "Hotline Bling", "Starset - Monster", "Þarký Olmasýn" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, -1));

        deðiþtirici.setBackground(new java.awt.Color(255, 255, 255));
        deðiþtirici.setForeground(new java.awt.Color(51, 51, 51));
        deðiþtirici.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                deðiþtiriciAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(deðiþtirici, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("GERÝ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 160, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/giphy (7).gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        oyunMuzigi MusicRun = new oyunMuzigi();
       
    private void deðiþtiriciAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_deðiþtiriciAncestorMoved
       
       deðiþtirici.addChangeListener(new ChangeListener() {
    public void stateChanged(ChangeEvent e) {
        float sesSeviyesi = (float) deðiþtirici.getValue() / 100.0f; 
    oyunMuzigi.sesSeviyesiniAyarla(sesSeviyesi);
    }
});
              
    }//GEN-LAST:event_deðiþtiriciAncestorMoved

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
            
       oyunMuzigi oyunMuzigi1= new oyunMuzigi();
        try {
            // TODO add your handling code here:
            Clip clip = AudioSystem.getClip();
        } catch (LineUnavailableException ex) {
            Logger.getLogger(AYARLAREKANÝ.class.getName()).log(Level.SEVERE, null, ex);
        }
     oyunMuzigi1.stopMusicc();
        if(ComboBox.getSelectedIndex()==0 ){
            oyunMuzigi.MusicRun("C:\\Users\\HP\\Documents\\NetBeansProjects\\ikinci deneme\\src\\res\\sidewalkandskeleton.wav");
        }
        else if (ComboBox.getSelectedIndex()==1){

            oyunMuzigi.MusicRun("C:\\Users\\HP\\Documents\\NetBeansProjects\\ikinci deneme\\src\\res\\sleepwalker.wav");
        }
        else if (ComboBox.getSelectedIndex()==2){

            oyunMuzigi.MusicRun("C:\\Users\\HP\\Documents\\NetBeansProjects\\ikinci deneme\\src\\res\\hotlinebling.wav");
        }
        else if (ComboBox.getSelectedIndex()==3){
             oyunMuzigi.MusicRun("C:\\Users\\HP\\Documents\\NetBeansProjects\\ikinci deneme\\src\\res\\Starset_Monster.wav");
        }
        else if (ComboBox.getSelectedIndex()==4){
            oyunMuzigi1.stopMusicc();
        }
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ilkEkran ilkEkran1 = new ilkEkran();
        ilkEkran1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public class VolumeSliderListener implements ChangeListener {
    public void stateChanged(ChangeEvent e) {
        Object volumeControl = null;
        Object volumeSlider = null;
        if (volumeSlider == null || volumeControl == null) return;
         float value = volumeSlider.getValue();
        volumeControl.setValue(value);
    }
}*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AYARLAREKANÝ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AYARLAREKANÝ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AYARLAREKANÝ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AYARLAREKANÝ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        oyunMuzigi araba = new oyunMuzigi();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AYARLAREKANÝ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    public javax.swing.JSlider deðiþtirici;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
