/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ikinci.deneme;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class karakterSecimi extends javax.swing.JFrame {

    /**
     * Creates new form karakterSecimi
     */
    public karakterSecimi() {
        initComponents();
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ilkpanel = new javax.swing.JPanel();
        demon = new javax.swing.JButton();
        human = new javax.swing.JButton();
        spirit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        baslat = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ilkpanel.setLayout(null);
        getContentPane().add(ilkpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, 0, 0));

        demon.setBackground(new java.awt.Color(51, 51, 51));
        demon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/demon.png"))); // NOI18N
        demon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demonActionPerformed(evt);
            }
        });
        getContentPane().add(demon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 100, 150));

        human.setBackground(new java.awt.Color(51, 51, 51));
        human.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/human.png"))); // NOI18N
        human.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humanActionPerformed(evt);
            }
        });
        getContentPane().add(human, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, 150));

        spirit.setBackground(new java.awt.Color(51, 51, 51));
        spirit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/spirit.png"))); // NOI18N
        spirit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spiritActionPerformed(evt);
            }
        });
        getContentPane().add(spirit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 150));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        baslat.setBackground(new java.awt.Color(51, 51, 51));
        baslat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        baslat.setText("BASLAT>>>");
        baslat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(baslat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(baslat)
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("<<<GERÝ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("KARAKTER ÖZELLÝKLERÝ BURDA GÖRÜNÜR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 440, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/giphy (7).gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ilkEkran ilkEkran1 = new ilkEkran();
        ilkEkran1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void spiritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spiritActionPerformed

        // TODO add your handling code here:,
        jLabel1.setText("o kadar da kötü olmasa gerek !?");
        jLabel1.setForeground(Color.black);
        Font font = new Font("Times New Roman", Font.PLAIN, 20);
        jLabel1.setFont(font);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_spiritActionPerformed

    private void demonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demonActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("kaçmasý gereken sen misin onlar mý");
        jLabel1.setForeground(Color.black);
        Font font = new Font("Times New Roman", Font.PLAIN, 20);
        jLabel1.setFont(font);
         jPanel2.setVisible(true);
    }//GEN-LAST:event_demonActionPerformed

    
    private void humanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humanActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("sadece hayatta kalmaya çalýþan bi insan(MI??)");
        jLabel1.setForeground(Color.black);
        Font font = new Font("Times New Roman", Font.PLAIN, 20);
        jLabel1.setFont(font);
         jPanel2.setVisible(true);
    }//GEN-LAST:event_humanActionPerformed
     
    
    private void baslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslatActionPerformed
        // TODO add your handling code here:
         gamePlay gamePlay1 = new gamePlay();
    if (jLabel1.getText().equals("kaçmasý gereken sen misin onlar mý")) {
        gamePlay1.getCharacter().setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/resizedemon.png")));
    } else if (jLabel1.getText().equals("sadece hayatta kalmaya çalýþan bi insan(MI??)")) {
        gamePlay1.getCharacter().setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/resizehuman.png")));
    } else if (jLabel1.getText().equals("o kadar da kötü olmasa gerek !?")) {
        gamePlay1.getCharacter().setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/resizespirit.png")));
    }
    gamePlay1.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_baslatActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karakterSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karakterSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karakterSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karakterSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new karakterSecimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton baslat;
    public javax.swing.JButton demon;
    public javax.swing.JButton human;
    public javax.swing.JPanel ilkpanel;
    private javax.swing.JButton jButton4;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton spirit;
    // End of variables declaration//GEN-END:variables
}
